name: Compilation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            flags: "-DPHAPLO_ENABLE_UNIT_TESTS=ON"
          - os: "macOS-latest"
            flags: ""

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release ${{ matrix.flags }} -B build -S . && \
        cmake --build build && \
        cmake --build build --target test
