name: Compilation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        sudo apt-get install -y libgtest-dev && \
        cmake -DCMAKE_BUILD_TYPE=Release "-DPHAPLO_ENABLE_UNIT_TESTS:BOOL=ON" -B build -S . && \
        cmake --build build && \
        cmake --build build --target test
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -B build -S . && \
        cmake --build build